# Generated by Django 3.2.7 on 2021-10-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='voes',
            new_name='votes',
        ),
    ]
